CREATE TABLE etl_task_cfg (
  task_id int ,
  task_name varchar(200)  ,
  table_name varchar(300)  ,
  remark varchar(200)  ,
  database_src varchar(100) ,
  task_obj varchar(300)  ,
  para1 varchar(150)  ,
  para2 varchar(150)  ,
  para3 varchar(300),
  log_home varchar(150)  ,
  log_file varchar(150)  ,
  task_group_id int ,
  cycle varchar(2)  ,
  prio_lvl int ,
  if_recall int ,
  if_wait int ,
  if_pre int ,
  if_val int ,
  add_user varchar(20)  ,
  add_time timestamp  ,
  update_user varchar(20)  ,
  update_time timestamp  ,
  type int ,
  offset varchar(20) ,
  offset_type varchar(10) ,
  freq varchar(200) ,
  owner varchar(100) ,
  wait_code varchar(100) ,
  recall_code varchar(100) ,
  timeout int ,
  recall_interval int ,
  recall_limit int ,
  success_code varchar(50) ,
  PRIMARY KEY (task_id)
);

CREATE TABLE etl_taskrela_cfg (
  task_id int ,
  task_pre_id int ,
  remark varchar(200),
  cycle_gap varchar(5) ,
  time_stamp timestamp ,
  PRIMARY KEY (task_id,task_pre_id,cycle_gap),
);

CREATE table etl_task_status(
  task_status_id	varchar(50)	,
  task_id	int(11)	,
  task_name	varchar(200)	,
  task_group_id	int(11)	,
  database_src	varchar(100)		,
task_obj	varchar(300)	,
para1	varchar(150)	,
para2	varchar(150)	,
para3	varchar(300)	,
log_path	varchar(150)	,
cycle	char(1)	,
time_id	varchar(10)	,
status	int(11)		,
sts_desc	text	,
if_wait	int(11)	,
if_recall	int(11)	,
if_pre	int(11)	,
prio_lvl	int(11)	,
recall_num	int(11)	,
run_num	int(11)	,
recall_interval	int(11)	 ,
recall_limit	int(11)		,
start_time	timestamp	,
end_time	timestamp	,
time_stamp	timestamp	,
type	int(11)	,
table_name	varchar(100)	,
cal_dt	varchar(20)	,
freq	varchar(300)	,
owner	varchar(255)	,
trigger_time	bigint(20)	,
wait_code	varchar(100)	,
recall_code	varchar(100)	,
success_code	varchar(100)	,
job_code	int(11)	,
running_prio	int(11)		,
timeout	int(11)		,
job_codemsg	varchar(300)	,
);

